language: python

script:
  - apt-get update
  - apt-get install -y libzbar-dev poppler-utils
  - python3 -m pip install -U .
  - python3 -m artexamscan.demo  
  - cd demo
  - python3 -m artexamscan.scan --roster=roster.xlsx scan.pdf
